version: '3'

services:
  jupyter:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./notebooks:/home/jovyan"
    ports:
      - "8888:8888"
    environment:
      - GRANT_SUDO=yes
